//* ADD

export const ADD_TODO_PENDING = 'ADD_TODO_PENDING';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';

//* Remove

export const REMOVE_TODO_PENDING = 'REMOVE_TODO_PENDING';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_ERROR = 'REMOVE_TODO_ERROR';

//* Edit

export const EDIT_TODO_PENDING = 'EDIT_TODO_PENDING';
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS';
export const EDIT_TODO_ERROR = 'EDIT_TODO_ERROR';

//* Complete
export const COMPLETE_TODO_PENDING = 'COMPLETE_TODO_PENDING';
export const COMPLETE_TODO_SUCCESS = 'COMPLETE_TODO_SUCCESS';
export const COMPLETE_TODO_ERROR = 'COMPLETE_TODO_ERROR';
